import type { GeekEvent } from '@geekalender/shared';

export const seedEvents: GeekEvent[] = [
  {
    id: 'mark-hamill-birthday',
    title: 'Mark Hamill',
    category: 'birthday',
    date: '1951-09-25',
    recursAnnually: true,
    franchise: 'Star Wars',
  },
  {
    id: 'doctor-who-premiere',
    title: 'Doctor Who premieres',
    category: 'tv',
    date: '1963-11-23',
    recursAnnually: true,
    franchise: 'Doctor Who',
  },
  {
    id: 'star-trek-premiere',
    title: 'Star Trek premieres',
    category: 'tv',
    date: '1966-09-08',
    recursAnnually: true,
    franchise: 'Star Trek',
  },
  {
    id: 'star-wars-release',
    title: 'Star Wars released',
    category: 'movie',
    date: '1977-05-25',
    recursAnnually: true,
    franchise: 'Star Wars',
  },
  {
    id: 'zelda-release',
    title: 'The Legend of Zelda released (JP)',
    category: 'game',
    date: '1986-02-21',
    recursAnnually: true,
    franchise: 'The Legend of Zelda',
  },
  {
    id: 'the-hobbit-published',
    title: 'The Hobbit published',
    category: 'book',
    date: '1937-09-21',
    recursAnnually: true,
    franchise: 'Middle-earth',
  },
  {
    id: 'action-comics-1',
    title: 'Action Comics #1 on sale',
    category: 'book',
    date: '1938-04-18',
    recursAnnually: true,
    franchise: 'Superman',
  },
  {
    id: 'harry-potter-birthday',
    title: 'Harry Potter',
    category: 'character',
    date: '1980-07-31',
    recursAnnually: true,
    franchise: 'Harry Potter',
  },
  {
    id: 'towel-day',
    title: 'Towel Day',
    category: 'fandom',
    date: '2001-05-25',
    recursAnnually: true,
    franchise: "The Hitchhiker's Guide to the Galaxy",
  },
  {
    id: 'cake-day',
    title: 'Cake Day',
    category: 'fandom',
    date: '2001-07-01',
    recursAnnually: true,
    franchise: "The Cake",
  },
];
